# CI build definition for https://ci.appveyor.com/project/olegsych/simply
# To learn more, see http://www.appveyor.com/docs/appveyor-yml

version: 0.1.0-build{build}

branches:
  only:
  - master

skip_tags: true

os: Visual Studio 2015

build_script:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- msbuild simply.sln /m /p:Platform=x86 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- msbuild simply.sln /m /p:Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
- vstest.console bin\debug\Win32\simply.assert.tests.dll /Platform:x86 /logger:Appveyor
- vstest.console bin\debug\x64\simply.assert.tests.dll /Platform:x64 /logger:Appveyor /inIsolation
- vstest.console bin\debug\Win32\simply.com.tests.dll /Platform:x86 /logger:Appveyor
- vstest.console bin\debug\x64\simply.com.tests.dll /Platform:x64 /logger:Appveyor /inIsolation
- vstest.console bin\debug\Win32\simply.utility.tests.dll /Platform:x86 /logger:Appveyor
- vstest.console bin\debug\x64\simply.utility.tests.dll /Platform:x64 /logger:Appveyor /inIsolation

after_test:
- nuget pack "src\simply.nuspec" -BasePath "src" -OutputDirectory "bin\debug" -Properties "version=%appveyor_build_version%"
- nuget pack "src\assert\simply.assert.nuspec" -BasePath "src\assert" -OutputDirectory "bin\debug" -Properties "version=%appveyor_build_version%"
- nuget pack "src\com\simply.com.nuspec" -BasePath "src\com" -OutputDirectory "bin\debug" -Properties "version=%appveyor_build_version%"
- nuget pack "src\utility\simply.utility.nuspec" -BasePath "src\utility" -OutputDirectory "bin\debug" -Properties "version=%appveyor_build_version%"

artifacts:
- path: bin\debug\*.nupkg

nuget:
  project_feed: true
  disable_publish_on_pr: true
